name: Add GSC's proof of ownership file

on:
  workflow_run:
    workflows: [deploy mkdocs]
    branches:
      - master
    types:
      - completed

jobs:
  update-gh-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # 前のジョブが成功した場合のみ実行
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 完全な履歴を取得（ブランチ間切り替えのため）

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages

      - name: Switch to gh-pages branch
        run: git checkout gh-pages

      - name: Copy file from master branch
        run: |
          git checkout master -- google290e6b23c164f08d.html

      - name: Commit changes
        run: |
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add google290e6b23c164f08d.html
          git commit -m "Add google290e6b23c164f08d.html from master branch"
      
      - name: Push to gh-pages branch
        run: git push origin gh-pages
